import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import { SignInButton, UserButton, useUser } from "@clerk/nextjs";
import Playmat from "~/pages/playmat";

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const user = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-start bg-gradient-to-b from-[#faf0e6] to-[#fff0db]">
        <nav className="flex w-full flex-wrap items-center justify-between bg-orange-100 px-8 py-1">
          <div className="mr-6 flex flex-shrink-0 items-center text-xl font-bold text-amber-900">
            PTCG Sandbox
          </div>
          <div className="block w-full flex-grow lg:flex lg:w-auto lg:items-center">
            <a
              href=""
              className="mr-4 mt-4 block text-amber-900 hover:text-amber-600 lg:mt-0 lg:inline-block"
            >
              New Sandbox
            </a>
            <a
              href=""
              className="mr-4 mt-4 block text-amber-900 hover:text-amber-600 lg:mt-0 lg:inline-block"
            >
              Load Sandbox
            </a>
            <a
              href=""
              className="mr-4 mt-4 block text-amber-900 hover:text-amber-600 lg:mt-0 lg:inline-block"
            >
              Puzzles
            </a>
          </div>
          <div className="mt-4 inline-block rounded border border-amber-900 px-4 py-2 text-sm leading-none text-amber-900 hover:border-transparent hover:bg-amber-900 hover:text-orange-100 lg:mt-0">
            {!user.isSignedIn && <SignInButton mode="modal"></SignInButton>}
            {user.isSignedIn && <UserButton afterSignOutUrl="/"></UserButton>}
          </div>
        </nav>
        <div className="p-8 h-full w-full">
          <div className="h-full w-full rounded-md border-4 border-white">
            <h1 className="text-left text-xl font-bold"><Playmat /></h1>
          </div>
        </div>
      </main>
    </>
  );
}
